services:
    admin.admin.brand:
        class: AdminBundle\Admin\BrandAdmin
        arguments: [~, AppBundle\Entity\Brand, AdminBundle:BrandAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Brand }
        public: true

    admin.admin.category:
        class: AdminBundle\Admin\CategoryAdmin
        arguments: [~, AppBundle\Entity\Category, AdminBundle:CategoryAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Category }
        public: true
