<?php

namespace AppBundle\Repository;

/**
 * PropertyValueRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PropertyValueRepository extends \Doctrine\ORM\EntityRepository
{
}
